services:
    doctrine.migrations_multiple_database.configuration:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Configuration\Configuration
        public: true

    doctrine.migrations_multiple_database.connection_configuration:
        class: Doctrine\Migrations\Configuration\Configuration
        public: false
        abstract: true

    doctrine.migrations_multiple_database.dependency_factory:
        class: Doctrine\Migrations\DependencyFactory
        public: false
        abstract: true

    doctrine_migrations.diff_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\DiffCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:diff' }

    doctrine_migrations.sync_metadata_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\SyncMetadataCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:sync-metadata-storage' }

    doctrine_migrations.versions_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\ListCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:list' }

    doctrine_migrations.current_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\CurrentCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:current' }

    doctrine_migrations.dump_schema_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\DumpSchemaCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:dump-schema' }

    doctrine_migrations.execute_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\ExecuteCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:execute' }

    doctrine_migrations.generate_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\GenerateCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:generate' }

    doctrine_migrations.latest_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\LatestCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:latest' }

    doctrine_migrations.migrate_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\MigrateCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:migrate' }

    doctrine_migrations.rollup_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\RollupCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:rollup' }

    doctrine_migrations.status_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\StatusCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:status' }

    doctrine_migrations.up_to_date_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\UpToDateCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:up-to-date' }

    doctrine_migrations.version_command:
        class: AvaiBookSports\Bundle\MigrationsMutlipleDatabase\Command\Doctrine\VersionCommand
        arguments:
            - '@doctrine.migrations_multiple_database.configuration'
        tags:
            - { name: 'console.command', command: 'doctrine:migrations:version' }